name: WebP Pixbuf CI [MSVC]
'on':
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python Dependencies
        run: pip install meson ninja
      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64
      - name: Build
        run: mkdir -p build
        run: meson build
        run: meson compile -C build
        run: meson test -C build --print-errorlogs
